// src/App.vue
<script lang="ts" setup>
import LivestreamHeader from "./components/Header.vue";
import LivestreamFooter from "./components/Footer.vue";
import DefaultLayout from "./layouts/DefaultLayout.vue";
import { ref } from "vue";
import NoStageLayout from "./layouts/NoStageLayout.vue";

let layouts = [
    ref("default-layout"),
    ref("no-stage-layout")
];

let activeLayout = ref(0);

function switchLayout() {
    activeLayout.value += 1;
    if (activeLayout.value == layouts.length) {
        activeLayout.value = 0;
    }
}
</script>

<template>
    <div id="app-container">
        <LivestreamHeader id="header" @SwitchLayout="switchLayout"/>
        <div id="layout-container">
            <DefaultLayout v-if="activeLayout === 0"/>
            <NoStageLayout v-if="activeLayout === 1"/>
        </div>
        <LivestreamFooter id="footer" />
    </div>
</template>

<style lang="scss">
@import "style.scss";

body {
    width: 1920px;
    height: 1080px;
    margin: 0;

    background: transparent;
}

#app-container {
    position: absolute;
    top: 0;
    left: 0;
    width: 1920px;
    height: 1080px;

    background-image: url("./assets/background.png");
    background-size: cover;

    overflow: hidden;

    @include flex-vertical;
}

#header {
    width: 100%;
    height: 125px;
    box-sizing: border-box;

    overflow: hidden;
}

#layout-container {
    position: relative;
    width: 100%;
    overflow: hidden;

    flex-grow: 1;
}


#footer {
    width: 100%;
    height: 93.75px;
}
</style>

// app/page.tsx
'use client';

import { useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import DefaultLayout from '@/components/DefaultLayout';
import NoStageLayout from '@/components/NoStageLayout';

export default function Home() {
  const [activeLayout, setActiveLayout] = useState(0);
  const layouts = ['default-layout', 'no-stage-layout'];

  const switchLayout = () => {
    setActiveLayout((prev) => {
      const next = prev + 1;
      return next >= layouts.length ? 0 : next;
    });
  };

  return (
    <div
      className="absolute top-0 left-0 w-[1920px] h-[1080px] bg-cover overflow-hidden flex-vertical"
      style={{ backgroundImage: "url('/images/background.png')" }}
    >
      <div className="w-full h-[125px] box-border overflow-hidden">
        <Header onSwitchLayout={switchLayout} />
      </div>

      <div className="relative w-full overflow-hidden flex-grow">
        {activeLayout === 0 && <DefaultLayout />}
        {activeLayout === 1 && <NoStageLayout />}
      </div>

      <div className="w-full h-[93.75px]">
        <Footer />
      </div>
    </div>
  );
}
