// src/components/danmakuArea.vue
<script setup lang="ts">
</script>

<template>
    <div class="container">
        <div class="danmaku-container">
            <div id="tl" class="marker"/>
            <div id="tr" class="marker"/>
            <div id="br" class="marker"/>
            <div id="bl" class="marker"/>
        </div>
        <h1>CHAT LOG</h1>
    </div>
</template>

<style scoped lang="scss">
    @import '../style.scss';
    
    .container {
        width: 100%;
        height: 100%;
        
        position: absolute;
        user-select: none;
    }

    h1 {
        color: white;
        background-color: $primary-accent-color;
        width: fit-content;
        font-family: outfit;
        padding: 0 0.25em;
        margin: 0.5em 0;
        
        font-size: 14px;
    }

    .danmaku-container {
        position: relative;
        background-color: hsla($primary-accent-color-H, $primary-accent-color-S, $primary-accent-color-L, 0.03);
        backdrop-filter: blur(4px);

        width: 100%;
        height: 100%;
    }

    .marker {
        height: 20%;
        width: 20%;

        border: 4px solid hsla($primary-accent-color-H, $primary-accent-color-S, $primary-accent-color-L, 0.8);
    }

    #tl {
        position: absolute;
        top: 0;
        left: 0;

        border-right: none;
        border-bottom: none;
    }

    #tr {
        position: absolute;
        top: 0;
        right: 0;

        border-left: none;
        border-bottom: none;
    }

    #br {
        position: absolute;
        bottom: 0;
        right: 0;

        border-left: none;
        border-top: none;
    }

    #bl {
        position: absolute;
        bottom: 0;
        left: 0;

        border-right: none;
        border-top: none;
    }
</style>

// components/DanmakuArea.tsx
'use client';

interface DanmakuAreaProps {
  className?: string;
}

export default function DanmakuArea({ className = "" }: DanmakuAreaProps) {
  return (
    <div className={`absolute w-full h-full select-none ${className}`}>
      <div className="relative bg-primary/[0.03] backdrop-blur-[4px] w-full h-full">
        <div className="absolute top-0 left-0 h-[20%] w-[20%] border-[4px] border-primary/80 border-r-0 border-b-0" />
        <div className="absolute top-0 right-0 h-[20%] w-[20%] border-[4px] border-primary/80 border-l-0 border-b-0" />
        <div className="absolute bottom-0 right-0 h-[20%] w-[20%] border-[4px] border-primary/80 border-l-0 border-t-0" />
        <div className="absolute bottom-0 left-0 h-[20%] w-[20%] border-[4px] border-primary/80 border-r-0 border-t-0" />
      </div>
      <h1 className="text-white bg-primary w-fit font-outfit px-[0.25em] my-2 m-0 text-[14px]">
        CHAT LOG
      </h1>
    </div>
  );
}
