// components/Footer.tsx
'use client';

import { useState, useEffect } from 'react';

export default function Footer() {
  const [footerText, setFooterText] = useState("少女折寿中...");
  const [showFooterText, setShowFooterText] = useState(true);

  const footerTexts = [
    "随便开播 随时下播 其实不是很建议点进来看...",
    "...这话我其实写直播间封面上了，不过我猜你肯定没看。",
    "这个遮罩是用vue写的！虽然一开始很难用但是习惯之后vue真是好文明.jpg",
    "如果主包突然没动静了可能是趣味生煎 也有可能是似了",
    "小毛龙终于把这个东西做完了然后决定自己占着不给香菇狐狸用",
    "其实我不知道这个字幕动画具体是怎么写出来的的 他莫名其妙动起来了",
    "群友问我什么时候搞sc我说现在这个弹幕量谁来发那都全是sc",
    "{Error Loading footer_banner_text[6]: Received Error [HTTP 502]}",
    "你好今天不是星期四但是请v我50我有一种称为碳水脂肪不足的综合症必须使用美国肯塔基一家尖端生物科技公司的最新型生物制剂进行治疗",
    "wei？zaima？",
  ];

  useEffect(() => {
    let displayFooterTextIndex = -1;

    const interval = setInterval(() => {
      setShowFooterText(false);
      displayFooterTextIndex += 1;

      if (displayFooterTextIndex === footerTexts.length) {
        displayFooterTextIndex = 0;
      }

      setFooterText(footerTexts[displayFooterTextIndex]);

      setTimeout(() => {
        setShowFooterText(true);
      }, 2000);
    }, 7000);

    return () => clearInterval(interval);
  }, []);

  const primaryAccentColorH = 200;
  const primaryAccentColorS = 100;
  const primaryAccentColorL = 47.6;
  const primaryAccentColorHCoefficient = 1.1355;

  return (
    <div className="relative h-full w-full bg-secondary">
      <div
        className="absolute right-0 top-0 w-[879px] h-full bg-cover z-10"
        style={{
          backgroundImage: "url('/images/footer-deco-1.png')",
          filter: `hue-rotate(${primaryAccentColorH * primaryAccentColorHCoefficient}deg) saturate(${primaryAccentColorS * 5}%) brightness(${primaryAccentColorL * 5}%)`,
        }}
      />
    </div>
  );
}

// src/components/Footer.vue
<script setup lang="ts">
import { ref } from "vue";

var footerText = ref("少女折寿中...");
var showFooterTexts = ref(true);

var displayFooterTextIndex: number = -1;

var footerTexts: string[] = [
    "随便开播 随时下播 其实不是很建议点进来看...",
    "...这话我其实写直播间封面上了，不过我猜你肯定没看。",
    "这个遮罩是用vue写的！虽然一开始很难用但是习惯之后vue真是好文明.jpg",
    "如果主包突然没动静了可能是趣味生煎 也有可能是似了",
    "小毛龙终于把这个东西做完了然后决定自己占着不给香菇狐狸用",
    "其实我不知道这个字幕动画具体是怎么写出来的的 他莫名其妙动起来了",
    "群友问我什么时候搞sc我说现在这个弹幕量谁来发那都全是sc",
    "{Error Loading footer_banner_text[6]: Received Error [HTTP 502]}",
    "你好今天不是星期四但是请v我50我有一种称为碳水脂肪不足的综合症必须使用美国肯塔基一家尖端生物科技公司的最新型生物制剂进行治疗",
    "wei？zaima？",
];

setInterval(function (): void {
    showFooterTexts.value = false;
    displayFooterTextIndex += 1;

    if (displayFooterTextIndex == footerTexts.length) {
        displayFooterTextIndex = 0;
    }

    footerText.value = footerTexts[displayFooterTextIndex];

    setTimeout(function (): void {
        showFooterTexts.value = true;
    }, 2000);
}, 7000);
</script>

<template>
    <div class="container">
        <div id="title-area">
            <img
                id="title-area-deco-img"
                src="../assets/footer-title-deco.png"
            />
            <p id="title-area-deco">XML<br />NEWS</p>
            <img id="title-area-globe" src="../assets/globe.png"/>
        </div>

        <div id="footer-texts-wrapper">
            <Transition>
                <p id="footer-texts" v-if="showFooterTexts">{{ footerText }}</p>
            </Transition>
        </div>

        <div id="deco-end" />
    </div>
</template>

<style scoped lang="scss">
@import "../style.scss";

.container {
    position: absolute;
    height: 100%;
    width: 100%;
    background-color: $secondary-accent-color;
}

#title-area {
    font-family: outfit;
    position: relative;
    top: 0;
    left: 0;
    width: 286.5px;
    height: 93.75px;

    background-color: $primary-accent-color;

    @include flex-horizontal;
}

#title-area-deco-img {
    height: 30px;
    margin: 0 31.875px;
}

#title-area-globe {
    position: absolute;
    height: 60px;
    right: 60px;
    z-index: 1;
}

#title-area-deco {
    margin: 0;
    color: white;

    font-size: 30px;
    text-shadow: 
        $primary-accent-color 3px 0 0, 
        $primary-accent-color 0 3px 0, 
        $primary-accent-color -3px 0 0, 
        $primary-accent-color 0 -3px 0;
    z-index: 10;
}

#footer-texts-wrapper {
    overflow: hidden;
    color: white;

    position: absolute;
    left: 286.5px;
    top: 0;
    width: calc(100% - 286.5px);
    height: 100%;

    padding-left: 1rem;

    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: start;

    overflow-x: hidden;

    z-index: 11;
}

#footer-texts {
    margin: 0;
    font-size: 30px;
    text-wrap: nowrap;
    white-space: nowrap;
    font-family: MiSans;

    z-index: 10;
}

#deco-end {
    position: absolute;
    right: 0;
    top: 0;

    width: 879px;
    height: 100%;

    background-image: url("../assets/footer-deco-1.png");
    background-size: cover;

    filter: hue-rotate(calc($primary-accent-color-H * $primary-accent-color-H-coefficient * 1deg))
        saturate(calc($primary-accent-color-S * 5%))
        brightness(calc($primary-accent-color-L * 5%));

    z-index: 10;
}

.v-enter-active {
    transition: all 1s ease-in-out;
}

.v-leave-active {
    transition: all 1s ease-in-out;
}

.v-enter-from {
    transform: translateX(20px);
    opacity: 0;
}


.v-leave-to {
    transform: translateX(100px);
    opacity: 0;
}
</style>
