// components/LivestreamTimer.tsx
'use client';

import { useState, useEffect, useRef } from 'react';

interface LivestreamTimerProps {
  className?: string;
}

export default function LivestreamTimer({ className = "" }: LivestreamTimerProps) {
  const [hoursElapsed, setHoursElapsed] = useState("??");
  const [minutesElapsed, setMinutesElapsed] = useState("??");
  const [secondsElapsed, setSecondsElapsed] = useState("??");
  const [framesElapsed, setFramesElapsed] = useState("??");
  const [isBlinking, setIsBlinking] = useState(false);

  const livestreamStartRef = useRef(new Date());

  useEffect(() => {
    const interval = setInterval(() => {
      const now = new Date();
      let elapsedTime = now.valueOf() - livestreamStartRef.current.valueOf();

      const hourElapsed = Math.floor(elapsedTime / (3600 * 1000));
      elapsedTime -= hourElapsed * 3600 * 1000;
      const minuteElapsed = Math.floor(elapsedTime / (60 * 1000));
      elapsedTime -= minuteElapsed * 60 * 1000;
      const secondElapsed = Math.floor(elapsedTime / 1000);
      elapsedTime -= secondElapsed * 1000;
      const millisecElapsed = elapsedTime;
      const frameElapsed = Math.floor(millisecElapsed / (1000/60));

      setHoursElapsed(hourElapsed >= 10 ? hourElapsed.toString() : "0" + hourElapsed.toString());
      setMinutesElapsed(minuteElapsed >= 10 ? minuteElapsed.toString() : "0" + minuteElapsed.toString());
      setSecondsElapsed(secondElapsed >= 10 ? secondElapsed.toString() : "0" + secondElapsed.toString());
      setFramesElapsed(frameElapsed >= 10 ? frameElapsed.toString() : "0" + frameElapsed.toString());
    }, 5);

    return () => clearInterval(interval);
  }, []);

  const resetLivestreamTimer = () => {
    startBlinking();
    setTimeout(() => {
      livestreamStartRef.current = new Date();
    }, 50);
  };

  const startBlinking = () => {
    setIsBlinking(true);
    setTimeout(() => {
      setIsBlinking(false);
    }, 200);
  };

  return (
    <div className={`${className}`}>
      <div
        className="flex-vertical items-start justify-end h-full select-none cursor-pointer"
        onClick={resetLivestreamTimer}
      >
        <div className="flex-horizontal items-end bg-white/20 backdrop-blur-[2px] w-full flex-grow">
          <div
            className={`flex-horizontal w-full font-outfit text-primary text-[18px] font-medium justify-start ${
              isBlinking ? 'animate-blink' : ''
            }`}
          >
            <p className="m-0 w-fit flex-horizontal justify-center">{hoursElapsed}</p>
            <p className="m-0 relative -top-[0.125em] mx-[0.1em]">:</p>
            <p className="m-0 w-fit flex-horizontal justify-center">{minutesElapsed}</p>
            <p className="m-0 relative -top-[0.125em] mx-[0.1em]">:</p>
            <p className="m-0 w-fit flex-horizontal justify-center">{secondsElapsed}</p>
            <p className="m-0 w-fit flex-horizontal justify-center ml-auto opacity-50">{framesElapsed}</p>
          </div>
        </div>
        <div className="w-full bg-primary font-outfit text-white text-[14px] font-bold px-[0.25em] opacity-90">
          LIVESTREAM TIMER
        </div>
      </div>
      <style jsx>{`
        @keyframes blink {
          0% { opacity: 0; }
          25% { opacity: 1; }
          50% { opacity: 0; }
          75% { opacity: 1; }
        }
        .animate-blink {
          animation: blink 0.4s 1 normal ease-in-out;
        }
      `}</style>
    </div>
  );
}

// src/components/LivestreamTimer.vue
<script setup lang="ts">
    import { ref, Ref } from 'vue'

    var hours_elapsed = ref("??")
    var minutes_elapsed = ref("??")
    var seconds_elapsed = ref("??")
    var frames_elapsed = ref("??")

    var livestream_start: Date = new Date();
    var isBlinking: Ref<boolean> = ref(false);

    setInterval(function(): void {
        let now: Date = new Date();
        
        let elapsed_time = now.valueOf() - livestream_start.valueOf();

        let hour_elapsed = Math.floor(elapsed_time / (3600 * 1000));
        elapsed_time -= hour_elapsed * 3600 * 1000;
        let mintue_elapsed = Math.floor(elapsed_time / (60 * 1000));
        elapsed_time -= mintue_elapsed * 60 * 1000;
        let second_elapsed = Math.floor(elapsed_time / 1000);
        elapsed_time -= second_elapsed * 1000;
        let milisec_elapsed = elapsed_time;
        let frame_elapsed = Math.floor(milisec_elapsed/(1000/60))

        hours_elapsed.value = (hour_elapsed >= 10 ? hour_elapsed.toString() : "0" + hour_elapsed.toString());
        minutes_elapsed.value = (mintue_elapsed >= 10 ? mintue_elapsed.toString() : "0" + mintue_elapsed.toString());
        seconds_elapsed.value = (second_elapsed >= 10 ? second_elapsed.toString() : "0" + second_elapsed.toString());
        frames_elapsed.value = (frame_elapsed >= 10 ? frame_elapsed.toString() : "0" + frame_elapsed.toString());

    }, 5);

    function resetLivestreamTimer() {
        startBlinking();
        setTimeout(() => {
            livestream_start = new Date();
        }, 50);
    }

    function startBlinking() {
        isBlinking.value = true;
        setTimeout(() => {
            isBlinking.value = false;
        }, 200);
    }
</script>

<template>
    <div id="wrapper">
        <div id="container" @click="resetLivestreamTimer">
            <div id="time" ref="timer">
                <div id="hms" :class="{ blinking: isBlinking }">
                    <p id="time-display-hr" class="time-number">{{ hours_elapsed }}</p>
                    <p class="time-separator">:</p>
                    <p id="time-display-min" class="time-number">{{ minutes_elapsed }}</p>
                    <p class="time-separator">:</p>
                    <p id="time-display-sec" class="time-number">{{ seconds_elapsed }}</p>
                    <p id="time-display-frame" class="time-number">{{ frames_elapsed }}</p>
                </div>
            </div>
            <div id="clock-prompt" >LIVESTREAM TIMER</div>
        </div>
    </div>
</template>

<style scoped lang="scss">
    @import "../style.scss";

    $clock-accent-color: $primary-accent-color;

    p {
        margin: 0;
    }

    
    #container {
        @include flex-vertical;

        align-items: start;
        justify-content: end;

        height: 100%;
        user-select: none;
    }

    #time {
        @include flex-horizontal;
        align-items: end;

        background-color: rgba(255, 255, 255, 20%);
        backdrop-filter: blur(2px);

        width: 100%;
        flex-grow: 1;
    }

    #hms {
        @include flex-horizontal; 
        width: 100%;

        font-family: outfit, sans-serif;
        color: $clock-accent-color;

        font-size: 18px;
        font-weight: 500;

        justify-content: start;

        &.blinking {
            animation: blink 0.4s 1 normal ease-in-out;
        }

        @keyframes blink {
            0% {
                opacity: 0;
            }
            25% {
                opacity: 1;
            }
            50% {
                opacity: 0;
            }
            75% {
                opacity: 1;
            }
        }
    }

    .time-display .time-number {
        width: fit-content;

        @include flex-horizontal;
        justify-content: center;
    }

    .time-separator, .date-separator {
        position: relative;
        top: -0.125em;
        margin: 0 0.1em;
        background-color: rgba(0, 0, 0, 0);
    }

    #date {
        font-size: 10px;
        justify-content: start;
        font-weight: 300;
    }

    #time-date {
        @include flex-horizontal;
    }

    #time-display-frame {
        margin-left: auto;
        opacity: 50%;
    }

    #clock-prompt {
        background-color: $clock-accent-color;
        font-family: outfit, sans-serif;
        color: white;
        box-sizing: border-box;
        padding: 0 .25em;

        font-size: 14px;
        font-weight: 700;

        width: 100%;
        opacity: 90%;
    }
</style>
