// components/Stage.tsx
'use client';

interface StageProps {
  className?: string;
}

export default function Stage({ className = "" }: StageProps) {
  const containerHeight = 838;
  const aspectRatio = 16 / 10;

  return (
    <div
      className={`bg-stage-background ${className}`}
      style={{
        width: `${containerHeight * aspectRatio}px`,
        height: `${containerHeight}px`,
      }}
    />
  );
}

// src/components/Stage.vue
<script setup lang="ts">
</script>

<template>
  <div class="container" />
</template>

<style scoped lang="scss">
    @import '../style.scss';
    $container-height: 838px;

    .container {
        width: calc($container-height * $stage-aspect-ratio-Width2Height);
        height: $container-height;

        background-color: $stage-background;
    }
</style>
