// components/InfoBlock.tsx
'use client';

import { useRef, useEffect, KeyboardEvent } from 'react';

interface InfoBlockProps {
  id: number;
  title: string;
  content: string;
  onRemove: (id: number) => void;
}

export default function InfoBlock({ id, title, content, onRemove }: InfoBlockProps) {
  const decoratorRef = useRef<HTMLDivElement>(null);
  const decoratorWrapperRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const decoratorWrapper = decoratorWrapperRef.current;
    const decorator = decoratorRef.current;

    if (!decoratorWrapper || !decorator) return;

    const handleMouseEnter = () => {
      decorator.classList.add('expanded');
    };

    const handleMouseLeave = () => {
      decorator.classList.remove('expanded');
    };

    const handleClick = () => {
      onRemove(id);
    };

    decoratorWrapper.addEventListener('mouseenter', handleMouseEnter);
    decoratorWrapper.addEventListener('mouseleave', handleMouseLeave);
    decoratorWrapper.addEventListener('click', handleClick);

    return () => {
      decoratorWrapper.removeEventListener('mouseenter', handleMouseEnter);
      decoratorWrapper.removeEventListener('mouseleave', handleMouseLeave);
      decoratorWrapper.removeEventListener('click', handleClick);
    };
  }, [id, onRemove]);

  const preventNewline = (event: KeyboardEvent<HTMLParagraphElement>) => {
    if (event.key === "Enter") {
      event.preventDefault();
      (event.target as HTMLElement).blur();
    }
  };

  return (
    <div className="flex-horizontal h-full w-fit items-start ml-8 whitespace-nowrap font-source-han-serif text-[rgb(50,50,50)]">
      <div ref={decoratorWrapperRef} className="w-5 h-full cursor-pointer">
        <div
          ref={decoratorRef}
          className="h-[6px] w-5 bg-primary transition-all duration-200 ease-out"
          style={{ willChange: 'height' }}
        />
      </div>
      <div className="flex-vertical items-start justify-start relative -top-[10px]">
        <p
          className="m-0 text-[25px] pl-[0.25em] min-w-[2em] whitespace-nowrap outline-none focus-visible:border-b-2 focus-visible:border-primary focus-visible:rounded-[2px]"
          contentEditable
          suppressContentEditableWarning
          onKeyDown={preventNewline}
        >
          {title}
        </p>
        <p
          className="m-0 pl-8 text-[35px] relative -top-[5px] whitespace-nowrap outline-none focus-visible:border-b-[3px] focus-visible:border-primary focus-visible:rounded-[3px]"
          contentEditable
          suppressContentEditableWarning
          onKeyDown={preventNewline}
        >
          {content}
        </p>
      </div>
      <style jsx>{`
        .expanded {
          height: 100% !important;
        }
      `}</style>
    </div>
  );
}

// src/components/header_components/InfoBlock.vue
<script setup lang="ts">
import { onMounted, Ref, ref, defineEmits } from "vue";

const props = defineProps({
    id: Number,
    title: String,
    content: String
});

const emits = defineEmits(["BlockRemoval"]);

const decorator: Ref<null | HTMLDivElement> = ref(null);
const decoratorWrapper: Ref<null | HTMLDivElement> = ref(null);

function preventNewline(event: KeyboardEvent) {
    if (event.key === "Enter") {
        event.preventDefault();
        (event.target as HTMLElement).blur();
    }
}

onMounted(() => {
    decoratorWrapper.value?.addEventListener("mouseenter", () => {
        decorator.value?.classList.add("expanded");
    });
    decoratorWrapper.value?.addEventListener("mouseleave", () => {
        decorator.value?.classList.remove("expanded");
    });
    decoratorWrapper.value?.addEventListener("click", () => {
        if (props.id) {
            emits("BlockRemoval", props.id);
        }
    });
})
</script>

<template>
  <div class="info">
        <div class="decorator-wrapper" ref="decoratorWrapper">
            <div class="decorator" ref="decorator"/>
        </div>
        <div class="info-content-wrapper">
            <p class="info-title" contenteditable="true" @keydown="preventNewline">{{ title }}</p>
            <p class="info-content" contenteditable="true" @keydown="preventNewline">{{ content }}</p>
        </div>
    </div>
</template>

<style scoped lang="scss">
    @import '../../style.scss';

    [contenteditable] {
        outline: 0 solid transparent;
    }

    p {
        white-space: nowrap;
    }

    .info {
        @include flex-horizontal;

        height: 100%;
        width: fit-content;

        align-items: start;

        margin-left: 2em;

        white-space: nowrap;
    }

    .decorator-wrapper {
        width: 20px;
        height: 100%;
    }

    .decorator {
        height: 6px;
        width: 20px;

        background-color: $primary-accent-color;
        transition: all 0.2s ease;

        &.expanded {
            height: 100%;
        }
    }

    .info-content-wrapper {
        @include flex-vertical;
        
        align-items: start;
        justify-content: start;

        position: relative;
        top: -10px;
    }

    .info-content-wrapper > p {
        margin: 0;
    }

    .info-title {
        font-size: 25px;
        padding-left: 0.25em;
        min-width: 2em;
    }

    .info-title:focus-visible {
        border-bottom: 2px solid $primary-accent-color;
        border-radius: 2px;
    }

    .info-content {
        padding-left: 2em;

        font-size: 35px;

        position: relative;
        top: -5px;
    }

    .info-content:focus-visible {
        border-bottom: 3px solid $primary-accent-color;
        border-radius: 3px;
    }
</style>
